### ISSUE TITLE
FTBFS with bliss 0.77

### ISSUE THREAD

**Issue by jengelh** [polymake/polymake#8]
polymake 4.4 fails to build with bliss-0.77:

```
[  380s] /home/abuild/rpmbuild/BUILD/polymake-4.4/bundled/bliss/apps/graph/src/GraphIso.cc: In constructor 'polymake::gr
aph::GraphIso::impl::impl(int, bool)':
[  380s] /home/abuild/rpmbuild/BUILD/polymake-4.4/bundled/bliss/apps/graph/src/GraphIso.cc:40:26: error: expected type-s
pecifier
[  380s]    40 |          src_graph = new bliss::Digraph(n_arg);
[  380s]       |                          ^~~~~
[  380s] /home/abuild/rpmbuild/BUILD/polymake-4.4/bundled/bliss/apps/graph/src/GraphIso.cc: In member function 'void polymake::graph::GraphIso::impl::set_color(int, int, int)':
[  380s] /home/abuild/rpmbuild/BUILD/polymake-4.4/bundled/bliss/apps/graph/src/GraphIso.cc:57:17: error: 'Digraph' is not a member of 'bliss'; did you mean 'Graph'?
[  380s]    57 |          bliss::Digraph* g = static_cast<bliss::Digraph*>(src_graph);
```

This is because Digraph is now in `<bliss/digraph.hh>` which is missing in GraphIso.cc.

```
[  380s] In file included from /usr/include/bliss/graph.hh:22,
[  380s]                  from /home/abuild/rpmbuild/BUILD/polymake-4.4/bundled/bliss/apps/graph/src/GraphIso.cc:20:
[  380s] /usr/include/bliss/abstractgraph.hh:204:106: note:   initializing argument 2 of 'const unsigned int* bliss::AbstractGraph::canonical_form(bliss::Stats&, const std::function<void(unsigned int, const unsigned int*)>&, const std::function<bool()>&)'
[  380s]   204 |                                      const std::function<void(unsigned int n, const unsigned int* aut)>& report = nullptr,
[  380s]       |                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
```

/usr/include/bliss/abstractgraph.hh now has:

```
  const unsigned int* canonical_form(Stats& stats,
                                     const std::function<void(unsigned int n, const unsigned int* aut)>& report = nullptr,
                                     const std::function<bool()>& terminate = nullptr);
```

**Comment by benlorenz** [comment]
Thanks for the report, please try this patch: https://polymake.org/downloads/bliss077.patch
At least locally all our tests succeed with this patch and the new bliss version. I am still in the progress of integrating the new bliss version into our CI server to run some further tests.

**Comment by jengelh** [comment]
Yeah, it's good.

**Comment by benlorenz** [comment]
Our CI is running with bliss 0.77 now, the patch is in master and will be included in the next release.
